name: CI

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  flatpak:
    runs-on: ubuntu-latest

    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged

    strategy:
      matrix:
        arch: [x86_64, aarch64]
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      
      # Docker is required by the docker/setup-qemu-action which enables emulation
      - name: Install deps
        run: |
          dnf -y install docker

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - uses: bilelmoussaoui/flatpak-github-actions@v2
        with:
          manifest-path: ch.laurinneff.AniList-GTK.json
          bundle: ch.laurinneff.AniList-GTK.flatpak
          cache-key: flatpak-builder-${{ github.sha }}
          arch: ${{ matrix.arch }}
