name: CI

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  flatpak:
    runs-on: ubuntu-latest

    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-41
      options: --privileged

    strategy:
      matrix:
        arch: [x86_64, aarch64]
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      
      # Docker is required by the docker/setup-qemu-action which enables emulation
      - name: Install deps
        run: |
          dnf -y install docker

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          manifest-path: ch.laurinneff.AniList-GTK.json
          bundle: ch.laurinneff.AniList-GTK.flatpak
          cache-key: flatpak-builder-${{ github.sha }}
          arch: ${{ matrix.arch }}

  win32:
    runs-on: windows-latest
    steps:
      - name: Prepare git
        run: |-
          git config --global core.autocrlf false
          git config --global core.eol lf
          
      - uses: actions/checkout@v2
      
      - uses: msys2/setup-msys2@v2
        with:
          msystem: CLANG64
          update: true
          install: mingw-w64-clang-x86_64-toolchain mingw-w64-clang-x86_64-gtk4  mingw-w64-clang-x86_64-libadwaita mingw-w64-clang-x86_64-json-glib mingw-w64-clang-x86_64-libsoup mingw-w64-clang-x86_64-libgee mingw-w64-clang-x86_64-meson mingw-w64-clang-x86_64-vala git
      
      - shell: powershell
        run: |
          cd build-aux\win32
          .\build.ps1
          
      - uses: actions/upload-artifact@v2
        with:
          name: windows-installer
          path: build-aux/win32/AniList-GTK Installer.exe
